In [2]:
print("hello world")


hello world


In [8]:
import tkinter as tk

class Calculator:
    def __init__(self, master):
        self.master = master
        master.title("Calculator")

        self.result_var = tk.StringVar()

        self.entry = tk.Entry(master, textvariable=self.result_var, font=('Arial', 24), bd=10, insertwidth=2, width=14, borderwidth=4)
        self.entry.grid(row=0, column=0, columnspan=4)

        self.create_buttons()

    def create_buttons(self):
        buttons = [
            '7', '8', '9', '/',
            '4', '5', '6', '*',
            '1', '2', '3', '-',
            '0', '.', '=', '+'
        ]

        row_val = 1
        col_val = 0

        for button in buttons:
            tk.Button(self.master, text=button, padx=20, pady=20, font=('Arial', 18),
                      command=lambda b=button: self.on_button_click(b)).grid(row=row_val, column=col_val)
            col_val += 1
            if col_val > 3:
                col_val = 0
                row_val += 1

        tk.Button(self.master, text='C', padx=20, pady=20, font=('Arial', 18),
                  command=self.clear).grid(row=row_val, column=0, columnspan=4)

    def on_button_click(self, char):
        if char == '=':
            try:
                result = eval(self.result_var.get())
                self.result_var.set(result)
            except Exception as e:
                self.result_var.set("Error")
        else:
            current_text = self.result_var.get()
            self.result_var.set(current_text + char)

    def clear(self):
        self.result_var.set("")


if __name__ == "__main__":
    root = tk.Tk()
    calculator = Calculator(root)
    root.mainloop()
    

In [ ]:
import tkinter as tk

class Calculator:
    def __init__(self, master):
        self.master = master
        master.title("Calculator")

        self.result_var = tk.StringVar()

        self.entry = tk.Entry(master, textvariable=self.result_var, font=('Arial', 24), bd=10, insertwidth=2, width=14, borderwidth=4)
        self.entry.grid(row=0, column=0, columnspan=4)

        self.create_buttons()

    def create_buttons(self):
        buttons = [
            '7', '8', '9', '/',
            '4', '5', '6', '*',
            '1', '2', '3', '-',
            '0', '.', '=', '+'
        ]

        row_val = 1
        col_val = 0

        for button in buttons:
            tk.Button(self.master, text=button, padx=20, pady=20, font=('Arial', 18),
                      command=lambda b=button: self.on_button_click(b)).grid(row=row_val, column=col_val)
            col_val += 1
            if col_val > 3:
                col_val = 0
                row_val += 1

        # Clear button
        tk.Button(self.master, text='C', padx=20, pady=20, font=('Arial', 18),
                  command=self.clear).grid(row=row_val, column=0, columnspan=2)

        # Backspace button
        tk.Button(self.master, text='←', padx=20, pady=20, font=('Arial', 18),
                  command=self.backspace).grid(row=row_val, column=2, columnspan=2)

    def on_button_click(self, char):
        if char == '=':
            try:
                result = eval(self.result_var.get())
                self.result_var.set(result)
            except Exception as e:
                self.result_var.set("Error")
        else:
            current_text = self.result_var.get()
            self.result_var.set(current_text + char)

    def clear(self):
        self.result_var.set("")

    def backspace(self):
        current_text = self.result_var.get()
        # Remove the last character
        self.result_var.set(current_text[:-1])


if __name__ == "__main__":
    root = tk.Tk()
    calculator = Calculator(root)
    root.mainloop()


: 

In [2]:
import numpy as np
numpy = np 
print(numpy)

<module 'numpy' from 'c:\\Users\\Salman\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>


In [3]:
import numpy as np 
array = np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [6]:
import numpy as np 
array = np.array([1,2,3,4])
print(array, array.ndim)

[1 2 3 4] 1


In [8]:
import numpy as np 
array = np.array([(1,2,3,4),(6,7,8,9)])
print(array, array.ndim)

[[1 2 3 4]
 [6 7 8 9]] 2


In [9]:
import numpy as np 
array = np.array([(1,2,3,4),(6,7,8,9),(10,11,12,13)])
print(array, array.ndim)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12 13]] 2


In [14]:
import numpy as np 
array = np.array([1,2,3,4,5])
print(array, array.ndim, array.size, array.shape, array.dtype)

[1 2 3 4 5] 1 5 (5,) int64


In [16]:
import numpy as np 
array = np.array([7])
print(array, array.ndim)

[7] 1


In [17]:
import numpy as np 
array = np.array([ [1,2],[3,4] ])
print(array, array.ndim)

[[1 2]
 [3 4]] 2


In [19]:
import numpy as np 
array = np.array([ [[1,2],[3,4]],[[5,6],[7,8]] ])
print(array, array.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 3


In [24]:
import numpy as np 
array = np.array([1,"hello",3,4])
print(array, array.ndim)
print(array[1])

['1' 'hello' '3' '4'] 1
hello


In [53]:
import numpy as np 
array = np.array([ [1,2,3],[4,5,6] ])
print(array, array.ndim)
print(array[0,1])

[[1 2 3]
 [4 5 6]] 2
2


In [52]:
import numpy as np 
array = np.array([ [[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]] ])
print(array, array.ndim)
print(array[1,0,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 3
8


In [7]:
import numpy as np

class NumPyCalculator:
    def __init__(self):
        pass

    def add(self, x, y):
        return np.add(x, y)

    def subtract(self, x, y):
        return np.subtract(x, y)

    def multiply(self, x, y):
        return np.multiply(x, y)

    def divide(self, x, y):
        try:
            return np.divide(x, y)
        except ZeroDivisionError:
            return "Error: Division by zero is undefined."

    def power(self, x, y):
        return np.power(x, y)

    def mod(self, x, y):
        return np.mod(x, y)

# Example usage:
if __name__ == "__main__":
    calc = NumPyCalculator()
    
    print("Addition: ", calc.add(10, 5))
    print("Subtraction: ", calc.subtract(10, 5))
    print("Multiplication: ", calc.multiply(10, 5))
    print("Division: ", calc.divide(10, 5))
    print("Power: ", calc.power(2, 3))
    print("Modulus: ", calc.mod(10, 3))

Addition:  15
Subtraction:  5
Multiplication:  50
Division:  2.0
Power:  8
Modulus:  1


In [3]:
import numpy as np

array  = [1,2,3]
array2 = [3,4,5]

arrconc = np.concatenate([array,array2])

arrconc

array([1, 2, 3, 3, 4, 5])

In [4]:
import numpy as np
array = np.array([[1,2,3,4], [5,6,7,8]])
print(array, array.ndim)

[[1 2 3 4]
 [5 6 7 8]] 2


In [6]:
import numpy as np

arr1 = [1,2,3,4,5]
arr2 = np.array([9,8,7])
print(arr1, arr2)

[1, 2, 3, 4, 5] [9 8 7]


In [7]:
# import numpy as np 
# arr1 = np.array([[1,2],[3,4]])
# arr2 = np.array([[5,6],[7,8]])
# arrconc = np.concatenate((arr1, arr2), axis=1)

In [8]:
arrconc

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [13]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr1 = np.array([6,7,8,9,0])

arrconc = np.stack((arr1, arr2), axis=1)

print(arrconc)

ValueError: all input arrays must have the same shape

In [15]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arrconc = np.stack((arr1, arr2), axis=2)
print(arrconc)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [19]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arrconc = np.hstack((arr1, arr2))
print(arrconc)

[[1 2 5 6]
 [3 4 7 8]]


In [27]:
import numpy as np 
array1 = np.array([1,2,3,4,5,6,])
spl = np.split(array1,2)
print(spl)

[array([1, 2, 3]), array([4, 5, 6])]


In [35]:
import numpy as np
array1 = np.array([1,2,3,4,5,6,7,8])

spl = np.array_split(array1,4)
print(spl)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [ ]:
import numpy as np


In [2]:
import pandas as pd

# Create a dictionary with the data
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],  
    'Age': [29, 34, 27, 25],                    
    'City': ['New York', 'Tokyo', 'London', 'Paris']
}


df = pd.DataFrame(data)


print(df)



    Name  Age      City
0   John   29  New York
1   Anna   34     Tokyo
2  Peter   27    London
3  Linda   25     Paris


In [19]:
import sys 
import pandas as pd
import matplotlib


matplotlib.use("Agg")

import matplotlib.pyplot as plt

df = pd.read_csv("salary.csv")

df.plot()

plt.savefig("output.png")
sys.stdout.flush()





In [4]:
import pandas as pd

df1 = pd.read_csv("shift.csv")

df1

Name Shift on Shift off
0   Daniel      8am       6pm
1  Lucifer     10pm       8am
2   Lupaiz     11am       9pm

In [5]:
import pandas as pd

df2 = pd.read_csv("salary.csv")

df2

Name Salary  Age  Experience
0  Daniel    50k   23         2.0
1    John    65k   22         2.5
2  Andrew    60k   25         3.0

In [6]:
import pandas as pd

df1 = pd.read_csv("shift.csv")
df2 = pd.read_csv("salary.csv")
df3 = pd.merge(df1,df2)
df3

Name Shift on Shift off Salary  Age  Experience
0  Daniel      8am       6pm    50k   23         2.0

In [22]:
import pandas as pd

# Correcting the dictionary syntax
data = {
    'Names': ['Andrew', 'Daniel', 'John', 'Lucifer'],  # Colon used instead of equal sign
    'Age': [23, 34, 76, 43],                           # Colon used instead of equal sign
    'Salary': [20000, 46000, 74000, 78000]             # Colon used instead of equal sign
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the DataFrame
print(df)


     Names  Age  Salary
0   Andrew   23   20000
1   Daniel   34   46000
2     John   76   74000
3  Lucifer   43   78000


In [23]:
import pandas as pd

# Create a DataFrame from a list of dictionaries

data = [
    {'Name': 'Andrew', 'Age': 23, 'Salary': 20000},
    {'Name': 'Daniel', 'Age': 34, 'Salary': 46000},
    {'Name': 'John', 'Age': 76, 'Salary': 74000},
    {'Name': 'Lucifer', 'Age': 43, 'Salary': 78000}
]

df = pd.DataFrame(data)

# Display the DataFrame

print(df)

import pandas as pd

# Create a DataFrame from a list of lists

data = [
    ['Andrew', 23, 20000],
    ['Daniel', 34, 46000],
    ['John', 76, 74000],
    ['Lucifer', 43, 78000]
]

df = pd.DataFrame(data, columns=['Name', 'Age', 'Salary'])

# Display the DataFrame

print(df)


      Name  Age  Salary
0   Andrew   23   20000
1   Daniel   34   46000
2     John   76   74000
3  Lucifer   43   78000
      Name  Age  Salary
0   Andrew   23   20000
1   Daniel   34   46000
2     John   76   74000
3  Lucifer   43   78000


In [24]:
import numpy as np 

df1 = np.array.read_csv("salary.csv")
df2 = np.array.read_csv("shift.csv")
df3 = np.merge(df1, df2)

print(df3)

AttributeError: 'builtin_function_or_method' object has no attribute 'read_csv'

In [25]:
import numpy as np

data = np.genfromtxt('salary.csv', delimiter=',', skip_header=1)
 
print(data)

[[ nan  nan 23.   2. ]
 [ nan  nan 22.   2.5]
 [ nan  nan 25.   3. ]]


In [27]:
import numpy as np

# Load the CSV file into a NumPy array, using np.genfromtxt to handle missing data
data = np.genfromtxt('salary.csv', delimiter=',', skip_header=1)

# Calculate the mean of each column, ignoring NaNs
col_means = np.nanmean(data, axis=0)

# Find indices where NaN values are present
nan_indices = np.where(np.isnan(data))

# Replace NaNs with the mean of the respective column
data[nan_indices] = np.take(col_means, nan_indices[1])

print("Data after replacing NaNs with column means:\n", data)


Data after replacing NaNs with column means:
 [[ nan  nan 23.   2. ]
 [ nan  nan 22.   2.5]
 [ nan  nan 25.   3. ]]


C:\Users\Salman\AppData\Local\Temp\ipykernel_14948\1979945065.py:7: RuntimeWarning: Mean of empty slice
  col_means = np.nanmean(data, axis=0)


Original Data:
[[ 1.          2.          3.          4.         28.75      ]
 [ 2.          4.          6.          8.         10.        ]
 [ 3.          6.          9.         12.         15.        ]
 [ 4.          8.         12.         22.66666667 20.        ]
 [ 5.         10.         15.         20.         25.        ]
 [ 6.         12.         18.         24.         30.        ]
 [ 7.         14.         21.         28.         35.        ]
 [ 8.         16.         24.         32.         28.75      ]
 [ 9.         18.         27.         36.         45.        ]
 [10.         20.         30.         40.         50.        ]]

Normalized Data:
[[0.         0.         0.         0.         0.46875   ]
 [0.11111111 0.11111111 0.11111111 0.11111111 0.        ]
 [0.22222222 0.22222222 0.22222222 0.22222222 0.125     ]
 [0.33333333 0.33333333 0.33333333 0.51851852 0.25      ]
 [0.44444444 0.44444444 0.44444444 0.44444444 0.375     ]
 [0.55555556 0.55555556 0.55555556 0.55555556 